# -*- coding: utf-8 -*-
"""Interquartile Range .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wqEFLpzXY1hO4pONruxWOW2wWQcMleyE
"""

import numpy as np
import matplotlib.pyplot as plt

# Sample data
data = [10, 12, 15, 18, 20, 22, 25, 28, 30]

# Calculate Quartiles
q1 = np.percentile(data, 25)
q2 = np.percentile(data, 50)  # Median
q3 = np.percentile(data, 75)

# Calculate IQR
iqr = q3 - q1

print("Q1 =", q1)
print("Median =", q2)
print("Q3 =", q3)
print("IQR =", iqr)

# Box Plot
plt.figure(figsize=(6,4))
plt.boxplot(data)
plt.title("Box Plot showing Interquartile Range (IQR)")
plt.ylabel("Values")
plt.grid(True)

plt.show()
Q1 = 15.0
Median = 20.0
Q3 = 25.0
IQR = 10.0